import Foundation
import Cocoa
import Combine

public enum FilterCategory: String, CaseIterable, Identifiable {
    case all = "All"
    case text = "Text"
    case code = "Code"
    case images = "Images"
    case screenshots = "Shots"
    case files = "Files"
    case pinned = "Pinned"
    case snippets = "Snippets"

    public var id: String { rawValue }

    public var icon: String {
        switch self {
        case .all: return "square.stack.3d.up"
        case .text: return "text.alignleft"
        case .code: return "chevron.left.forwardslash.chevron.right"
        case .images: return "photo"
        case .screenshots: return "camera.viewfinder"
        case .files: return "doc"
        case .pinned: return "pin.fill"
        case .snippets: return "bookmark"
        }
    }

    func matches(_ item: ClipboardItem) -> Bool {
        switch (self, item.type) {
        case (.all, _): return true
        case (.text, .text), (.code, .code), (.images, .image),
             (.screenshots, .screenshot), (.files, .file), (.snippets, .snippet): return true
        case (.pinned, _): return item.isPinned
        default: return false
        }
    }
}

public final class ClipboardManager: ObservableObject {
    public static let shared = ClipboardManager()

    @Published public private(set) var items: [ClipboardItem] = [] {
        didSet { recomputeFilteredItems() }
    }
    @Published public var selectedCategory: FilterCategory = .all {
        didSet { recomputeFilteredItems() }
    }
    @Published public var searchQuery: String = "" {
        didSet { recomputeFilteredItems() }
    }
    @Published public private(set) var selectedIndex: Int = 0
    @Published public private(set) var selectedItemId: UUID?
    @Published public private(set) var filteredItems: [ClipboardItem] = []

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int = 0
    private var monitorTimer: Timer?
    private var retentionTimer: Timer?
    private var settingsObservers: Set<AnyCancellable> = []
    private var settings: SettingsStore { .shared }

    private let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "PasteboardType.transient"
    ]

    /// Formatted-text types kept for "paste with formatting".
    private let richTypes: [NSPasteboard.PasteboardType] = [.rtf, .html]
    private let maxRichBytes = 2 * 1_048_576

    private init() {
        lastChangeCount = pasteboard.changeCount
        loadInitialData()
        startMonitoring()
        setupScreenshotIntegration()
        observeSettings()
    }

    private func observeSettings() {
        let s = settings
        Publishers.Merge(s.$maxItems.map { _ in () }, s.$retention.map { _ in () })
            .dropFirst(2)
            .debounce(for: .milliseconds(300), scheduler: RunLoop.main)
            .sink { [weak self] in self?.enforceLimits() }
            .store(in: &settingsObservers)

        s.$customScreenshotFolder
            .dropFirst()
            .receive(on: RunLoop.main)
            .sink { _ in ScreenshotManager.shared.restartMonitoring() }
            .store(in: &settingsObservers)

        // Re-check retention hourly so "1 day" really means a day.
        let t = Timer(timeInterval: 3600, repeats: true) { [weak self] _ in self?.enforceLimits() }
        RunLoop.main.add(t, forMode: .common)
        retentionTimer = t
    }

    // MARK: - Filtering & selection

    public func recomputeFilteredItems() {
        let query = searchQuery.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()

        let source: [ClipboardItem] = selectedCategory == .snippets
            ? SnippetManager.shared.sorted.map(\.asClipboardItem)
            : items.filter { selectedCategory.matches($0) }

        let filtered = source.filter { item in
            guard !query.isEmpty else { return true }
            return item.title.lowercased().contains(query)
                || item.previewText.lowercased().contains(query)
                || (item.fullText?.lowercased().contains(query) ?? false)
                || (item.filePath?.lowercased().contains(query) ?? false)
                || (item.sourceAppName?.lowercased().contains(query) ?? false)
                || (item.keyword?.lowercased().contains(query) ?? false)
        }

        let result = selectedCategory == .snippets ? filtered : filtered.sorted {
            if $0.isPinned != $1.isPinned { return $0.isPinned }
            return $0.timestamp > $1.timestamp
        }

        filteredItems = result

        if let currentId = selectedItemId, let idx = result.firstIndex(where: { $0.id == currentId }) {
            selectedIndex = idx
        } else if !result.isEmpty {
            // Keep the cursor near where it was (e.g. after deleting a row).
            let idx = min(selectedIndex, result.count - 1)
            selectedIndex = idx
            selectedItemId = result[idx].id
        } else {
            selectedIndex = 0
            selectedItemId = nil
        }
    }

    /// Called every time the overlay opens: fresh search, all categories, newest clip selected.
    public func resetForPresentation() {
        if !searchQuery.isEmpty { searchQuery = "" }
        if selectedCategory != .all { selectedCategory = .all }
        syncSelectionToFirst()
    }

    public func syncSelectionToFirst() {
        selectedIndex = 0
        selectedItemId = filteredItems.first?.id
    }

    public func selectNext() {
        guard !filteredItems.isEmpty else { return }
        selectedIndex = min(filteredItems.count - 1, selectedIndex + 1)
        selectedItemId = filteredItems[selectedIndex].id
    }

    public func selectPrevious() {
        guard !filteredItems.isEmpty else { return }
        selectedIndex = max(0, selectedIndex - 1)
        selectedItemId = filteredItems[selectedIndex].id
    }

    public func selectItem(id: UUID) {
        if let idx = filteredItems.firstIndex(where: { $0.id == id }) {
            selectedIndex = idx
            selectedItemId = id
        }
    }

    public func selectCategoryNext() {
        let all = FilterCategory.allCases
        if let idx = all.firstIndex(of: selectedCategory) {
            selectedCategory = all[(idx + 1) % all.count]
        }
    }

    public func selectCategoryPrevious() {
        let all = FilterCategory.allCases
        if let idx = all.firstIndex(of: selectedCategory) {
            selectedCategory = all[(idx - 1 + all.count) % all.count]
        }
    }

    public func getSelectedItem() -> ClipboardItem? {
        if let id = selectedItemId, let found = filteredItems.first(where: { $0.id == id }) {
            return found
        }
        return filteredItems.indices.contains(selectedIndex) ? filteredItems[selectedIndex] : filteredItems.first
    }

    public func count(for category: FilterCategory) -> Int {
        items.filter { category.matches($0) }.count
    }

    // MARK: - Monitoring

    public func startMonitoring() {
        monitorTimer?.invalidate()
        let timer = Timer(timeInterval: 0.3, repeats: true) { [weak self] _ in
            self?.checkPasteboard()
        }
        // .common so polling continues while menus are open or the list is scrolling.
        RunLoop.main.add(timer, forMode: .common)
        monitorTimer = timer
    }

    public func stopMonitoring() {
        monitorTimer?.invalidate()
        monitorTimer = nil
    }

    /// Marks a pasteboard write made by ClipBoardUltra itself so it is not re-recorded.
    public func acknowledgeInternalChange(_ changeCount: Int) {
        lastChangeCount = changeCount
    }

    private func setupScreenshotIntegration() {
        ScreenshotManager.shared.onNewScreenshot = { [weak self] screenshotItem in
            DispatchQueue.main.async {
                guard let self, self.settings.captureScreenshots, !self.settings.isPaused else { return }
                self.addItem(screenshotItem)
            }
        }
        ScreenshotManager.shared.startMonitoring()
    }

    private func loadInitialData() {
        var saved = StorageManager.shared.loadHistory()
        let existingPaths = Set(saved.compactMap { $0.filePath })

        if settings.captureScreenshots {
            for sc in ScreenshotManager.shared.fetchRecentScreenshotItems(limit: 10) {
                if let p = sc.filePath, !existingPaths.contains(p) {
                    saved.append(sc)
                }
            }
        }

        // Drop screenshots whose file has since been deleted.
        saved.removeAll { item in
            if case .screenshot = item.type, let p = item.filePath {
                return !FileManager.default.fileExists(atPath: p)
            }
            return false
        }

        saved.sort { $0.timestamp > $1.timestamp }
        items = applyingLimits(to: saved)
        StorageManager.shared.pruneOrphanedImages(activeItems: items)
    }

    private func checkPasteboard() {
        let currentCount = pasteboard.changeCount
        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        guard !settings.isPaused else { return }
        guard let types = pasteboard.types, !types.isEmpty else { return }
        if types.contains(where: { concealedTypes.contains($0.rawValue) }) { return }

        let frontmost = NSWorkspace.shared.frontmostApplication
        if settings.isIgnored(bundleID: frontmost?.bundleIdentifier) { return }
        let frontmostApp = frontmost?.localizedName

        // 1. Files copied in Finder (checked first: they also carry an icon image and a name string).
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           let url = urls.first {
            guard settings.captureFiles else { return }
            let path = url.path
            let size = (try? FileManager.default.attributesOfItem(atPath: path)[.size] as? NSNumber)?.int64Value
            let extra = urls.count > 1 ? " +\(urls.count - 1) more" : ""
            addItem(ClipboardItem(
                type: .file(path: path),
                title: url.lastPathComponent + extra,
                previewText: path,
                filePath: path,
                sourceAppName: frontmostApp,
                byteSize: size
            ))
            return
        }

        // 2. Text. Checked before images because apps like Excel, Numbers, Keynote and
        //    browsers put a rendered picture of the selection next to the text.
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            guard settings.captureText else { return }
            if settings.ignoreSecrets && SecretDetector.looksSecret(string) {
                print("[Clipboard] Skipped a clip that looks like a password or key")
                return
            }
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            let language = CodeDetector.detect(string)
            let firstLine = trimmed.components(separatedBy: .newlines).first?
                .trimmingCharacters(in: .whitespaces) ?? ""

            var item = ClipboardItem(
                type: language.map { .code(language: $0) } ?? .text,
                title: firstLine.isEmpty ? "Snippet" : String(firstLine.prefix(120)),
                previewText: String(trimmed.prefix(600)),
                fullText: string,
                sourceAppName: frontmostApp,
                charCount: string.count,
                lineCount: string.components(separatedBy: .newlines).count
            )
            item.richRelativePath = captureRichText(from: types)
            addItem(item)
            return
        }

        // 3. Images (copied pictures, ⌃⇧⌘4 screenshots to clipboard, etc.)
        guard settings.captureImages else { return }
        if let image = NSImage(pasteboard: pasteboard), image.size.width > 2, image.size.height > 2,
           let saved = StorageManager.shared.saveImage(image) {
            if let limit = settings.maxImageBytes, saved.byteSize > limit {
                print("[Clipboard] Skipped image larger than \(settings.maxImageMB) MB")
                StorageManager.shared.deleteImage(named: saved.relativePath)
                return
            }
            if let first = items.first, first.contentHash == saved.hash {
                StorageManager.shared.deleteImage(named: saved.relativePath)
                return
            }
            addItem(ClipboardItem(
                type: .image,
                title: "Image \(Int(saved.width)) × \(Int(saved.height))",
                previewText: "Copied image",
                imageRelativePath: saved.relativePath,
                imageWidth: saved.width,
                imageHeight: saved.height,
                sourceAppName: frontmostApp,
                byteSize: saved.byteSize,
                contentHash: saved.hash
            ))
        }
    }

    /// Saves RTF/HTML that came with copied text so it can be pasted with formatting later.
    private func captureRichText(from types: [NSPasteboard.PasteboardType]) -> String? {
        var rich: [String: Data] = [:]
        for type in richTypes where types.contains(type) {
            if let data = pasteboard.data(forType: type), data.count <= maxRichBytes {
                rich[type.rawValue] = data
            }
        }
        return StorageManager.shared.saveRichData(rich)
    }

    // MARK: - Limits

    /// Applies retention (age) and the maximum history size. Pinned clips are always kept.
    private func applyingLimits(to list: [ClipboardItem]) -> [ClipboardItem] {
        var result = list
        if let maxAge = settings.retention.interval {
            let cutoff = Date().addingTimeInterval(-maxAge)
            result.removeAll { !$0.isPinned && $0.timestamp < cutoff }
        }
        while result.count > settings.maxItems, let lastUnpinned = result.lastIndex(where: { !$0.isPinned }) {
            result.remove(at: lastUnpinned)
        }
        let kept = Set(result.map(\.id))
        for removed in list where !kept.contains(removed.id) {
            StorageManager.shared.deleteAssets(of: removed)
        }
        return result
    }

    public func enforceLimits() {
        let limited = applyingLimits(to: items)
        guard limited.count != items.count else { return }
        items = limited
        StorageManager.shared.saveHistory(items)
    }

    // MARK: - Mutations

    public func addItem(_ item: ClipboardItem) {
        // Remove older copies of the same content, but keep their pin.
        var wasPinned = false
        var updated = items
        updated.removeAll { existing in
            let same = (item.fullText != nil && existing.fullText == item.fullText)
                || (item.filePath != nil && existing.filePath == item.filePath)
                || (item.contentHash != nil && existing.contentHash == item.contentHash)
            if same {
                wasPinned = wasPinned || existing.isPinned
                if let img = existing.imageRelativePath, img != item.imageRelativePath {
                    StorageManager.shared.deleteImage(named: img)
                }
                if let rich = existing.richRelativePath, rich != item.richRelativePath {
                    StorageManager.shared.deleteRichData(named: rich)
                }
            }
            return same
        }

        var newItem = item
        newItem.isPinned = wasPinned
        updated.insert(newItem, at: 0)

        items = applyingLimits(to: updated)
        StorageManager.shared.saveHistory(items)
    }

    /// Moves a clip to the top of history after it has been pasted or copied.
    public func promote(_ item: ClipboardItem) {
        guard settings.promoteOnUse, let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        var updated = items
        var moved = updated.remove(at: index)
        moved.timestamp = Date()
        updated.insert(moved, at: 0)
        items = updated
        StorageManager.shared.saveHistory(items)
    }

    public func togglePin(for item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].isPinned.toggle()
        StorageManager.shared.saveHistory(items)
    }

    public func deleteItem(_ item: ClipboardItem) {
        StorageManager.shared.deleteAssets(of: item)
        items.removeAll { $0.id == item.id }
        StorageManager.shared.saveHistory(items)
    }

    public func clearAllUnpinned() {
        for item in items where !item.isPinned {
            StorageManager.shared.deleteAssets(of: item)
        }
        items = items.filter { $0.isPinned }
        StorageManager.shared.saveHistory(items)
    }
}

// MARK: - Code detection

/// Scores text for code-like structure instead of matching single words, so prose such as
/// "let me know" or "print (this)" stays plain text.
enum CodeDetector {
    private static let lineStarters: [String] = [
        "func ", "def ", "class ", "struct ", "enum ", "import ", "from ", "export ", "const ",
        "let ", "var ", "return ", "if (", "if let ", "guard ", "for (", "while (", "switch ",
        "public ", "private ", "#include", "#import", "package ", "fn ", "impl ", "interface ",
        "async ", "await ", "try ", "catch", "} else", "SELECT ", "INSERT ", "UPDATE ", "DELETE ",
        "CREATE ", "@", "//", "/*", "<?php", "echo ", "sudo ", "npm ", "git ", "cd ", "brew "
    ]

    static func detect(_ text: String) -> String? {
        let sample = String(text.prefix(4000))
        let lines = sample.components(separatedBy: .newlines).filter { !$0.trimmingCharacters(in: .whitespaces).isEmpty }
        guard !lines.isEmpty else { return nil }

        // Long flowing prose is never code.
        let words = sample.split(whereSeparator: { $0.isWhitespace }).count
        let symbols = sample.filter { "{}()[];=<>$|&".contains($0) }.count
        let symbolRatio = Double(symbols) / Double(max(sample.count, 1))

        var score = 0.0
        for line in lines.prefix(80) {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if lineStarters.contains(where: { trimmed.hasPrefix($0) }) { score += 1.5 }
            if let last = trimmed.last, ";{}):".contains(last) { score += 1 }
            if line.hasPrefix("    ") || line.hasPrefix("\t") { score += 0.5 }
            if trimmed.contains(" = ") || trimmed.contains("=>") || trimmed.contains("->") { score += 0.5 }
        }
        if symbolRatio > 0.04 { score += 2 }
        if symbolRatio < 0.01 && words > 12 { score -= 3 }

        if lines.count == 1 {
            let t = lines[0].trimmingCharacters(in: .whitespaces)
            if t.hasPrefix("http://") || t.hasPrefix("https://") || t.hasPrefix("mailto:") { return nil }
            let shellStarters = ["sudo ", "npm ", "npx ", "git ", "cd ", "brew ", "pip ", "curl ", "docker ", "kubectl ", "ls ", "mkdir ", "swift ", "python3 ", "chmod "]
            if shellStarters.contains(where: { t.hasPrefix($0) }) && words <= 20 { return "Shell" }
            // One-liners need a code-ish start plus real code syntax (assignment, braces,
            // or a call like foo(...)), so "let me know… print (this)" stays text.
            let startsLikeCode = lineStarters.contains(where: { t.hasPrefix($0) })
            let hasSyntax = ["=", ";", "{", "}", "->", "=>", "::"].contains(where: { t.contains($0) })
                || t.range(of: #"[A-Za-z_]\("#, options: .regularExpression) != nil
            guard hasSyntax && (startsLikeCode || symbolRatio > 0.08) else { return nil }
            return language(of: sample)
        }

        let threshold = max(3.0, Double(min(lines.count, 20)) * 0.6)
        guard score >= threshold else { return nil }
        return language(of: sample)
    }

    private static func language(of s: String) -> String {
        if s.contains("import SwiftUI") || s.contains("import Foundation") || s.contains("guard let ")
            || (s.contains("func ") && s.contains("->")) || s.contains("@Published") { return "Swift" }
        if s.contains("def ") && s.contains(":") || s.contains("import numpy") || s.contains("__init__")
            || s.contains("self.") && s.contains("def ") { return "Python" }
        if s.contains("<!DOCTYPE") || s.contains("<html") || s.contains("</div>") { return "HTML" }
        if s.contains("interface ") && s.contains(": string") || s.contains(": number") { return "TypeScript" }
        if s.contains("console.log") || s.contains("=>") || s.contains("const ") || s.contains("function ") { return "JavaScript" }
        if s.range(of: #"(?i)\bselect\b.+\bfrom\b"#, options: .regularExpression) != nil { return "SQL" }
        if s.contains("fn ") && s.contains("let mut") || s.contains("impl ") { return "Rust" }
        if s.contains("package main") || s.contains("func main()") { return "Go" }
        if s.hasPrefix("#!") || s.contains("sudo ") || s.contains("npm ") || s.contains("git ")
            || s.contains("brew ") || s.contains("echo ") { return "Shell" }
        if s.contains("{") && s.contains("\":") { return "JSON" }
        if s.contains("{") && s.contains("}") && s.contains(":") && s.contains(";") { return "CSS" }
        return "Code"
    }
}
